### ISSUE TITLE
Problem with Python requirements

### ISSUE THREAD

**Issue by wasteland93** [warthele/WText#1]
Hi Mr. Derfoufi,

I was trying to start main.py after cloning your project but Python returned the following error: 
`Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from tkinter import *
ModuleNotFoundError: No module named 'tkinter'
`
Could you please help me or add information to the documentation ?

Thanks in advance.

**Comment by warthele** [comment]
Hello,
It is an addiction problem.
I haven't added it to README.md yet and I apologize.
You need to install the tkinter library.

(My name is not M. Derfoufi I had the beginnings of the code in a site, then I improved it. I forgot to remove the name of the old author)
